### ISSUE TITLE
Have a fallback if cookies are being disabled or blocked

### ISSUE THREAD

**Issue by mtn** [uncommonhacks/makes18#1]
Related: we need to handle when javascript isn't supported by unhiding all relevant information.

There might be a better way to check if a person is blocking cookies than this, but one simple way is to try and set them and then revert to a default it they don't get updated properly. We can figure out exactly what we want the default to be, but it could be something like "name=celery".

**Comment by ghost** [comment]
I’m so happy this is happening :)
